### PR TITLE
Init demo

### PR DESCRIPTION
**Pull request by nelsonic**
@SimonLab this PR creates the demo app and deploys to Fly.io: https://gitea-demo.fly.dev/ 🚀 

Please review + merge when you can. 🙏 
Thanks again for your work on the `gitea` package. 🎉

### CODE REVIEW

**Comment by nelsonic** [comment]
Working on `localhost`:
image

Working on deploying to Fly.io now.

**Comment by nelsonic** [comment]
Deployed to Fly.io: https://gitea-demo.fly.dev/
image

**Comment by nelsonic** [comment]
@SimonLab this is ready for review. Thanks. ☀️

**Review by SimonLab — APPROVED** [review]
LGTM

**Pull request merged**
